### ISSUE TITLE
git://git.tuxfamily.org/gitroot/non/fltk.git mentioned in README is dead, please replace the NTK dependency with a working one

### ISSUE THREAD

**Issue by yurivict** [openAVproductions/openAV-Sorcer#32]
https://github.com/openAVproductions/openAV-Sorcer/blob/master/CMakeLists.txt#L18

**Comment by AVDambeck** [comment]
I know this isn't a super active project, but I'm really fond of sorcer. The NTK repo is dead. I still have a working copy on one computer, but I can't compile without it. I don't know how easy it is to replace, but I hope its not too hard. I really like this synth. Its straight forward and light weight

**Comment by yurivict** [comment]
Here's the NTK tarball that can be used: https://git.kx.studio/non/ntk/archive/v1.3.1001.tar.gz

**Comment by harryhaaren** [comment]
Thanks @yurivict, I've added a 2nd link for NTK, as was suggested for other NTK-using Repos such as Luppp, marking as fixed.
